php-cs-fixer:
    extends: .ci-php-script-launcher
    rules:
        - !reference [.ci-php-script-launcher, rules]
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          changes: ['src/**/*.php']
    variables:
        SCRIPT: 'php-cs-fixer:dry'
